### ISSUE TITLE
localization with InterfaceStrings

### ISSUE THREAD

**Issue by lobsam** [OpenPecha/Pecha.org#273]
### Descriptions: 
This issue deals with implementation and logic building for language toggle in pecha.org

### Implementation steps:

- [x] implement/extract all languages from string.js
- [x] Add Chinese( 中文 ) in header dropdown language
- [x] Edit and build logic for toggle multiple language in middleware.py file
- [x] edit/ update sefaria.js to handle multiple language (for react component)
