### ISSUE TITLE
make sure that all the localization strings are correctly used on the website - DJANGO side

### ISSUE THREAD

**Issue by Lungsangg** [OpenPecha/Pecha.org#375]
## Current situation

all the messages that Sefaria had split in many strings are now single strings with placeholders

## Todo

- [ ] check that all the tibetan strings in Figma are single strings in Tolgee with placeholders
- [ ] check that all the new translations from Figma are applied on the website and that they are in Tolgee
- [ ] add tag "figma" to all strings that are in Figma
- [ ] Ensure that all the strings that needed to be updated/added/removed as described in Figma have been processed correctly

Note: please make sure that the strings behind placeholders are also in Tolgee (like ཟླ། བདུན། ཉིན། and the numbers ༡ ༢ ༣ etc.)
