### ISSUE TITLE
[RFC00158]: revamp webfonts + font-families attribution

### ISSUE THREAD

**Issue by Lungsangg** [OpenPecha/Pecha.org#402]
# current situation

the serif/ sans-serif attribution in Sefaria doesn't correspond to our needs for Tibetan. So there is nothing much but hacks that can be done in the current situation.

# Solution

each language should be treated independently from the others so that no interference happens.
we should have the ability to set the size/font/color/etc. for each part of the website for each locale.

# Implementation steps

## Step 1 (Lungsang)
- [x] Reset the font groupings to its initial Sefaria state

## Step 2 (Lungsang) 
- [x] check in the card with the required sizes and fonts what needs to be modified
- [x] write documentations in wiki about existing grouping system [wiki link](https://github.com/OpenPecha/Pecha.org/wiki/Pecha.org-String-Grouping)
- [x] when applying different color and size for tibetan and english, there shouldnt be any changes on the other language. 
     - [x] Search a solution
     - [x] write documentation [wiki link](https://github.com/OpenPecha/Pecha.org/wiki/Pecha.org-String-Grouping#when-applying-different-color-and-size-for-tibetan-and-english-there-shouldnt-be-any-changes-on-the-other-language)
     - [x] Implement the solution in code 
          - Text page
          - Topics page
          - Community page
          - Profile page
          - Collection page
          - Account setting page
          - Registration page
          - Resources

## Texts main page

- [x] main header: sans-serif 18px black

![Image](https://github.com/user-attachments/assets/e298df04-32ca-4993-a135-ecbe223c7ba8)

- [x] search: serif 16pt

![Image](https://github.com/user-attachments/assets/9c47b587-4c18-4e58-b7ec-d14fffcad197)

- [x] description: sans-serif 17pt

![Image](https://github.com/user-attachments/assets/de0700b3-6ed5-4f0c-baa6-f4c699368c9c)

- [x] ཡིག་མཛོད་ཀྱི་དཀར་ཆ་ལ་ལྟ།: 17pt

![Image](https://github.com/user-attachments/assets/41071ca7-9e5b-403e-83ae-634e003a407a)

- [x] categories: 24pt

![Image](https://github.com/user-attachments/assets/da042218-405d-4a7d-9210-d4d72b87ebba)

- [x] category description: serif 16px

![Image](https://github.com/user-attachments/assets/e53f15a8-4574-4cf5-b0a1-c5b18238d24a)

## Text

- [x] category of text: 17px

![Image](https://github.com/user-attachments/assets/41057720-66ea-4626-8b9b-c6a9bd66bbb8)

- [x] versions: 20px

![Image](https://github.com/user-attachments/assets/6f0bf3c7-3724-4a21-88aa-af1d039ff447)

- [x] version title: serif 20px

![Image](https://github.com/user-attachments/assets/42453c23-a96e-4a8e-ba92-c884b0943661)

- [x] version history: sans-serif 15px

![Image](https://github.com/user-attachments/assets/ef8ecf7b-cc3b-43c1-81c3-e72bd1a869ab)

- [x] ཕབ་ལེན།: 20px

![Image](https://github.com/user-attachments/assets/eb79b954-c0a5-4964-bd31-a4ecb08e5d51)

## Reader App

- [x] resources: sans-serif 18px

![Image](https://github.com/user-attachments/assets/0f0f681e-18a7-4343-89fb-8666a4a45abd)

- [x] menu items: serif 18px

![Image](https://github.com/user-attachments/assets/48ad977b-6f7e-4a2a-94ee-c4e73593ab83)

- [x] menu categories: sans-serif 16px

![Image](https://github.com/user-attachments/assets/87a3e42e-9f2c-45c6-a533-4cd2c8144a04)

- [x] search message: 18px

![Image](https://github.com/user-attachments/assets/2c78c271-1b02-42b8-b973-f843591e6740)

- [x] buttons: serif 18px

![Image](https://github.com/user-attachments/assets/edb29776-8dc3-4413-bac5-ff8252e20768)

- [x] ལུང་འགོད་སའི་ཟིན་བྲིས་འདེམས།: 18px

![Image](https://github.com/user-attachments/assets/5d231716-ffd3-4807-b5cc-e17db3880895)

## Topics

- [x] topics search: 16px

![Image](https://github.com/user-attachments/assets/0bcdd5da-7fe0-4385-98ca-a8a7d7610849)

- [x] ཀ་ཁ་: 26px

![Image](https://github.com/user-attachments/assets/346a2757-ad50-40e9-95a6-610938d11872)

- [x] New Sheet buttons: serif 16px

![Image](https://github.com/user-attachments/assets/c6c0b890-f713-48b7-aa08-6be5382bdbf5)

## Community

- [ ] Join the conversation: serif 28px ---- seems like this is disabled

![Image](https://github.com/user-attachments/assets/1eebd5d1-1255-4bf4-be01-05c75efb2d7f)

## Bookmarks

- [x] History: sans-serif 18px

![Image](https://github.com/user-attachments/assets/97bfa5b9-01d2-4a3f-855a-036d6bbeaf96)

- [x] date: sans-serif 14px

![Image](https://github.com/user-attachments/assets/0be71b42-96d3-48dc-8af4-a2d72c505fa1)

## Profile menu

- [x] menu items: serif 17px

![Image](https://github.com/user-attachments/assets/a62e8280-75ad-4dc2-bcf3-0932d09755ec)

- [x] logout: serif 17px

![Image](https://github.com/user-attachments/assets/ecd4f685-d084-423e-a323-d535924779c8)

## Profile

- [x] buttons: 18px

![Image](https://github.com/user-attachments/assets/42b220b4-fd4b-432b-911f-1eeaffa3e200)

- [x] Sheets-collections-comments menu: 20px

![Image](https://github.com/user-attachments/assets/a2d44bea-3432-4bd4-b6ac-802a64e8e2db)

**Comment by Lungsangg** [comment]
PECHA.ORG FONT GROUPING :
 
 ```
 - Nav Bar
 
 -- Title
 -- Description
 -- learn more
 
 
 
 - Button 
 
 -- Start Reading, make a sheet, explore collection, load more, edit profile, Setting, Add Picture, Create a New Sheet, Create a New Collection, Cancel, Save, login, Send Reset Link, Sign Up, Add note, Go to My Notes, Select Version, Select Format, Filter
 
 -- Follower, Following, follow
 
 
 - Place_holder
 -- serif for text related
 -- sans-serif for non-text related
 
 
 - Text Page
 
 -- Texts(Library), Topics, Community
 -- Browse the Library, Explore by Topic, Topic(2nd category), 
 -- Recently Published(community)
 
 -- Title (Category) (same for topic)
 -- Short Description (Category) (same for topic)
 
 -- Upper level category title (eg; prayer)
 
 -- Title (Book)
 -- Root level category (eg: Liturgy)
 -- Version Title(Book)
 -- Content, Versions, Source, Sheets 
 -- Revision History, Source: etc
 -- Version language name
 
 
 
 -- Main Text page (Title, Content)
 --- Text Title (Note: discuss with samdup)
 --- Section Title (1,2 etc   see in ཀུན་བཟང་སྨོན་ནམ་)
 --- Segment number 
 --- Header Title 
 --- Header subtitle
 

 -- Text Display Settings (LANGUAGE, LAYOUT, FONT SIZE)

 
 - Complext Text
 -- TOC (kunsang monlam)
 
 -- Revision History :
 --- Title
 --- Subtitle
 --- Version history content(entry)
 --- older activity
 
 
 
 
 - Topic Page
 
 - Topic main page
 
 -- Title
 -- root level category
 -- description

 --- Source tab (Description)
 
 --- bookmark pop up, three dot pop up
 
 --- Sheets tab
 ---- sheet title english(tib and eng both - botok)
 ---- sheet title tibetan 
 
 
 - Sort (Recent, View)
 
 - Sheet Page 
 -- Title (botok)
 -- Author
 -- Content
 
 
 - Resources 
 ་
 -- Header Title
 -- Title
 
 -- list (About this text, Table of Contents, Search in this Text, Topics, Add to Sheet, Compare Text, Notes, Share)
 -- Related texts title (serif)  --- eg: Commentary, རྩ་བ་མིང་
 -- numbers in resources
 
 
 -- Text and version Selection
 --- select button
 --- translation select (blue color)
 

 
 -- About this text
 --- Title
 --- Text title
 --- Text category (eg: commentary)
 --- Revision History (comes from text revision history?)
 
 
 -- Table of Contents
 --- Title (chapter)
 --- numbers

 
 -- Search in this Text
 --- Total (with number)   --- to localize
 --- result title
 --- result body
 --- result match
 --- result origin
 
 -- Translations 
 --- title 
 --- language title (section)
 --- preview
 --- translation title
 
 -- Web Pages (བསྟན་འབར་མ་)
 --- domain link
 --- number
 --- link title 
 --- domain 
 --- citing
 
 -- Topics 
 --- title
 --- topic description
 --- three dot description
 --- no result text 
 
 -- Related text
 --- title 
 --- number
 --- title gray
 --- Description
 
 -- Inside one related text
 --- Title
 --- gray title 
 --- preview
 --- button text
 
 
 
 -- Add to sheet
 --- title (selected Citation, Add to)
 --- Dropdown list
 --- name new sheet (placeholder)
 
 -- Compare Text
 
 -- Note
 --- place holder 
 --- actual written text
 
 
 
 
 -- Share a Link
 --- title
 --- description (need to add )
 --- share link content
 --- social media share text (twitter logo need to change)
 
 
 -- Learn more page
 --- Title
 --- title desc
 --- content
 
 
 - Profile 
 
 -- username
 -- website link text
 
 -- 4 Tabs : Sheets, Collections, Notes,  Buddhist Text Tracker
 
 --- Under Sheets tab
 ---- Title
 ---- Descriptions (publish, view, date)
 
 --- Under Collections tab
 ---- Title
 ---- detail(number of sheets, listed or unlisted text)
 ---- 
 
 --- Under Notes tab
 ---- Title
 ---- number of notes
 
 --- Buddhist Text Tracker
 ---- User name
 ---- Hide User ID - need to fix
 ---- two tab
 ---- Titles
 ---- numbers
 
 
 -- Edit profile 
 --- main title 
 --- field name (eg: Pinned sheets, email)
 --- field desc
 --- add a line button
 --- text field 
 
 ---- Section title (public sheets, contact)
 ---- section sub title
 ---- sheets title
 
 -- Account Settings
 --- field name, toggle button
 --- Google account comment
 
 

 
 
 
 
 
 
 - Saved Page
 -- Options (save, history)
 -- Content
 
 - Notification
 -- Title
 -- content
 
 - Help
 
 - Account setting
 
 - Registration :
 
 - Dropdown : revision history dropdown, sign up, download text
 ```

**Comment by drupchen** [comment]
Font sizes don't correspond

**Comment by drupchen** [comment]
@Lungsangg webfont not applied

- [x] 1. 

![Image](https://github.com/user-attachments/assets/753f33cd-e6ae-4fd2-9ac9-a20de8392434)

- [x] 2.

![Image](https://github.com/user-attachments/assets/81c4b851-369e-473f-8ff2-3718057548e1)

- [x] 3. ཧེ་བྲུ། is not webfont

![Image](https://github.com/user-attachments/assets/f67a2120-9a51-421f-8022-1c386c58699a)

- [x] 4. བཟོ་བཅོས་ཀྱི་ལོ་རྒྱུས། and ཨིན་ཇི། and སྒྲིག་བཞིན་ཡོད།

![Image](https://github.com/user-attachments/assets/49926b4e-386f-4868-9819-c9358dee26ec)

- [x] 5. https://dev.pecha.org/The_Way_of_the_Bodhisattva.5.12?lang=he&with=Translations&lang2=he

![Image](https://github.com/user-attachments/assets/b17ca67f-77cf-42dc-bb6d-7edec7786553)

- [x] 6. https://dev.pecha.org/The_Way_of_the_Bodhisattva.5.12?lang=he&with=Sheets&lang2=he inside འབྲེལ་ཡོད་ཟིན་བྲིས།

![Image](https://github.com/user-attachments/assets/ae7844c3-6392-465a-afc4-714156e1215c)

- [x] 7. https://pecha.org/topics/from-suffering-to-happiness?tab=sheets བདེ་སྐྱིད། and སྡུག་བསྔལ་བདེ་བར་བསྒྱུར་ཐབས།

![Image](https://github.com/user-attachments/assets/229e17e8-ea7f-4232-9e83-d874b05efc09)

- [x] 8. not applied

![Image](https://github.com/user-attachments/assets/4e3ce1a2-6ee6-4313-882d-c5bd8aba2183)

- [x] 9. not applied in search results

![Image](https://github.com/user-attachments/assets/a4e16cc2-4238-474e-ada8-5242cda79634)

- [x] 10. new sheet

![Image](https://github.com/user-attachments/assets/9baf3542-9284-4239-ab62-2e99ce9a104d)

**Comment by Lungsangg** [comment]
@drupchen la, looks like we have disabled "join the conversation" title in community page, so i didn't applied the text size.

**Comment by Lungsangg** [comment]
- [x] https://dev.pecha.org/The_Way_of_the_Bodhisattva.5.12?lang=he&p2=sheet&s2=85&lang2=he

- [x] ![Image](https://github.com/user-attachments/assets/23d15094-fd66-42d9-91dc-a42f56e7d1a7)

- [x] ![Image](https://github.com/user-attachments/assets/e1fbb327-a30c-4308-91b7-bd69d4943702)

- [x] translation selection string in resource

![Image](https://github.com/user-attachments/assets/c2a5a2c6-d71d-44af-ac31-65fbb3b2fa2c)


- [x] ![Image](https://github.com/user-attachments/assets/2363ee39-9707-477a-840e-fc90cd86ff10)

- [x] input string when write text on མཆན། གཞན་གྱིས་མཐོང་མི་ཐུབ། place holder
 ![Image](https://github.com/user-attachments/assets/ce320acd-e95b-4853-b1bd-3f9fcb3c6a10)

**Comment by Lungsangg** [comment]
@drupchen la, Right now i couldn't find any solution to load webfont on form placeholder. So login and register form placer holder doesn't have webfont right now.  I will continue to look into it and push the changes once i found a solution for it.
