### ISSUE TITLE
Add "share" button

### ISSUE THREAD

**Issue by Lungsangg** [OpenPecha/Pecha.org#413]
## Location

- open a text that has commentaries (chojuk)
- in Resources, click on "Commentary"
- click to preview the commentary

## Wanted

add a "Share" button between "add to sheet" and "remove"

Notes: 
- the component is the same as when sharing a segment of any text
- the icon should also be the same icon, scaled down to fit with the other icons

## Implementation Steps 

- [x] share component usage test
- [x] commentary tool component test
- [x] add share component to commentary tool

**Comment by drupchen** [comment]
icon is missing:

![Image](https://github.com/user-attachments/assets/2110cdcb-f95f-4af0-9f21-6dd4a4aa1c0a)

**Comment by Lungsangg** [comment]
![Image](https://github.com/user-attachments/assets/f2fa3a73-550c-42da-9f03-40450c6acb0b)
@drupchen la its solved
