### ISSUE TITLE
[RFC0073] Text Page (pecha.org) 

### ISSUE THREAD

**Issue by lobsam** [OpenPecha/Pecha.org#64]
# [RFC0073] Text Page (pecha.org) 

##Housekeeping
This RFC is related to [RFW0072](https://github.com/OpenPecha/Pecha.org/issues/52)

## Named Concepts

Reactjs : A frontend develoment tool.
MongoDB: A NoSql database to store and manage Text data

## Dependencies
-

## Summary

The task involves creating of Text landing page in which list of all Texts is available. On clicking particular Text route to selected Text page. 
End-user can able to view all Texts available in Pecha.org Text landing page. and these text can be of muti-lingual (as of now in Tibetan and English)
All the above task can be done by using Reactjs (use to develop frontend app ),  MongoDB (use to store Text data) and python/django (use to manage and setup APIs)

## Testing
   - Unit testing : Pecha.org should be run and debug locally before pushing it to Staging stage.

## Work Phases
Non coding Preparation :
- [x] Planning

Implementation
- [x] OpenPecha/Pecha.org#60
      Estimated time:  30 min
      Actual time:  
- [x] OpenPecha/Pecha.org#63
      Estimated time:  3 hr
      Actual time:  
- [x] OpenPecha/Pecha.org#62
     Estimated time:  3 hr
      Actual time:
- [x] OpenPecha/Pecha.org#61
     Estimated time:  4 hr
      Actual time:

Tesing
 - [ ] Unit Testing 
     Estimated time:  4 hr
      Actual time:
 

## Reviewed By
@tenkus47
